### PR TITLE
Update Brainstorm import script (hardcoded fiducials)

### PR DESCRIPTION
**Pull request by ftadel**

### CODE REVIEW

**Comment by ftadel** [comment]
I was a bit too enthusiastic about what I did before, I realized there were some issues with the script...
I ended up placing all the fiducials manually for all the volumes, instead of re-using part of what you had done. It has no impact on coregistration, only on the display on the Brainstorm side.

Maybe you should wait I post a reply on the Brainstorm forum before merging the PR this time :)

**Comment by christian-oreilly** [comment]
@ftadel Yeah, I kinda had the feeling that I was going a bit fast by merging it right away without letting it simmer a bit to see potential problems coming up to the surface... I'll control my impulsive itches this time :)

**Comment by ftadel** [comment]
It's ready to merge now, I'm all done :)

**Comment by ftadel** [comment]
Happy summer!

**Comment by christian-oreilly** [comment]
Alright, if you say so! I'll merge then! Have a nice summer too @ftadel !

**Pull request merged**
